name: default vehicles publish to store.nanos.world

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish package
    steps:
      - uses: actions/checkout@v2
      - name: Nanos Store Action
        uses: nanos-world/nanos-store-action@3bbac33644dd1fe8fb6d4e316af4918bb6a11f65
        with:
          # folder which contains the asset/package - if it's on root, leave it blank
          folder: ''
          # name of the asset/package
          name: 'default-vehicles'
          # changelog of the release - can be edited on the store before it gets published
          changelog: 'built through actions'
          # API token - generate at https://store.nanos.world/settings/tokens/ and set under Settings -> Secrets -> Actions with name STORE_SECRET
          token: ${{ secrets.STORE_SECRET }}
